In [ ]:
import numpy as np


In [ ]:
data1 = [1, 2, 3,4 ]
list = np.array(data1)
list

data1 = [[1, 2, 3], [4, 5, 6]]
list = np.array(data1)
list

In [ ]:
list.shape

In [ ]:
list

In [ ]:
list[0, 0:]

In [ ]:
np.ones(10)

In [ ]:
np.ones((3, 5))

In [ ]:
np.arange(10)

In [ ]:
type(list)

In [ ]:
np.ones_like(list)

In [ ]:
np.identity(5)

In [ ]:
np.eye(3)

In [ ]:
from pandas import Series
from pandas import DataFrame

In [ ]:
obj = Series([10, 20, 30, 40], ['a', 'b', 'c', 'd'])
obj
obj = Series(obj, index = [1, 'b'])
obj

In [ ]:
obj2 = Series(obj, index=['a','e'])
obj2

In [ ]:
obj.index = [1,2,3,4]
obj

In [ ]:
dic = {'states': ['GA', 'CA', 'TN'],
       'population': [10000, 20000, 5000]}

df = DataFrame(dic)
df

In [ ]:
df.states

In [ ]:
df.ix[0]

In [ ]:
df.index = [10, 20 , 30]

In [ ]:
#df

import numpy as np

In [ ]:
df = DataFrame(np.arange(9).reshape(3, 3), index = [1,2,3], columns = ['GA', 'TN', 'CA'])
type(df)
df.ix[1]

In [ ]:
df.reindex([1,5, 10, 11])

In [ ]:
import numpy as np

def simulate_prizedoor(n):
    return np.random.randint(0, 3, n)
    
    
def simulate_guess(n):
    return np.zeros(n, dtype=np.int64)
    
#simulate_prizedoor(10)    
simulate_guess(10)

In [ ]:
a = True
type(a)

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
         [4,5,6,]])


In [ ]:
arr[0:1,:]

In [ ]:
x = [1,2,3]
y = [4,5,6]
zipped = zip(x,y)
print zip(*zipped)
unzipped_x, unzipped_y = zip(*zipped)
print unzipped_x
print unzipped_y

In [ ]:
import numpy as np
arr = [[1,2,3],[4,5,6]]
arr1 = np.array(arr)

In [ ]:
arr1[1,2]

In [10]:
arr1[1,]

array([4, 5, 6])

In [11]:
arr1[1,::2]

array([4, 6])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])